jobs:
  test:
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
      SOLR_DOCKER_IMAGE_REPO: github-pr/solr
      SOLR_DOCKER_IMAGE_TAG: ${{github.event.number}}
    name: Build and test Docker image
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-package: jdk
        java-version: 11
    - continue-on-error: true
      name: Install ACL
      run: sudo apt-get install acl
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-docker-${{ hashFiles('versions.lock') }}
        path: '~/.gradle/caches

          '
        restore-keys: '${{ runner.os }}-gradle-docker-

          ${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Build Docker image with Gradle
      run: ./gradlew solr:docker:docker
    - continue-on-error: true
      name: Run tests on Docker image
      run: ./gradlew solr:docker:testDocker
name: Docker Build & Test
on:
  repository_dispatch:
    types: trigger-ga___docker-test.yml
