jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/labeler@v5
      with:
        sync-labels: true
name: Pull Request Labeler
on:
  repository_dispatch:
    types: trigger-ga___labeler.yml
