jobs:
  test:
    env:
      GRADLE_ENTERPRISE_ACCESS_KEY: ${{ secrets.GE_ACCESS_TOKEN }}
    name: Run SolrJ Tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        distribution: temurin
        java-package: jdk
        java-version: 11
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-solrj-${{ hashFiles('versions.lock') }}
        path: '~/.gradle/caches

          '
        restore-keys: '${{ runner.os }}-gradle-solrj-

          ${{ runner.os }}-gradle-

          '
    - continue-on-error: true
      name: Test the SolrJ Package
      run: ./gradlew solr:solrj:test
name: SolrJ Tests
on:
  repository_dispatch:
    types: trigger-ga___solrj-test.yml
