jobs:
  stale:
    permissions:
      actions: write
      pull-requests: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/stale@v9
      with:
        days-before-close: -1
        days-before-issue-stale: -1
        days-before-pr-stale: 60
        exempt-draft-pr: true
        operations-per-run: 30
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-pr-label: stale
        stale-pr-message: 'This PR had no visible activity in the past 60 days, labeling
          it as stale. Any new activity will remove the stale label. To attract more
          reviewers, please tag someone or notify the dev@solr.apache.org mailing
          list. Thank you for your contribution!

          '
name: Mark stale pull requests
on:
  repository_dispatch:
    types: trigger-ga___stale.yml
