jobs:
  test:
    name: Run Solr Tests using Crave.io resources
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Destroy previous clone
      run: crave clone destroy -y /crave-devspaces/pipeline/runs/${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}
        || echo "Clone did not exist"
    - continue-on-error: true
      name: Crave clone sources
      run: crave clone create --projectID 39 /crave-devspaces/pipeline/runs/${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}
    - continue-on-error: true
      name: Checkout the correct branch
      run: 'git -C /crave-devspaces/pipeline/runs/${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}
        fetch origin ${GITHUB_REF}:${GITHUB_REF}

        git -C /crave-devspaces/pipeline/runs/${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}
        checkout ${GITHUB_REF}

        '
    - continue-on-error: true
      name: Initialize, build, test
      run: 'cd /crave-devspaces/pipeline/runs/${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}

        crave run --clean

        '
    - continue-on-error: true
      name: Delete Clone
      run: crave clone destroy -y /crave-devspaces/pipeline/runs/${GITHUB_RUN_ID}_${GITHUB_RUN_NUMBER}
name: Solr Tests
on:
  repository_dispatch:
    types: trigger-ga___tests-via-crave.yml
